### PR TITLE
export YSETTINGS_FILE

### PR DESCRIPTION
**Pull request by dana-resonai**

### CODE REVIEW

**Comment by itamaro** [comment]
just one question. why?

**Comment by dlehavi-resonai** [comment]
@itamaro : Modi requested it, IIRC so jenkins will have easier time (or actually a more sensible way) of finding YSetting

**Comment by itamaro** [comment]
@dlehavi-resonai I'm unable to tag Modi for some reason. @modi-resonai can you share more context about this change?

**Comment by dlehavi-resonai** [comment]
@itamaro I'll ask @modi-resonai to reply when he's here (he's on this PR)

**Comment by dana-resonai** [comment]
@itamaro  you can take a look at this PR: https://github.com/resonai/resonai2/pull/1124
In different places Modi and other people needed to get the BASE_ENV_VERSION param from Settings.
Till now he did this with grep on the file.
I suggested to add a python script that loads the settings module, just like ybt does, and take the constant from there.
This PR is in order to be able to import the constant of the Settings location from ybt

**Comment by modi-resonai** [comment]
@itamaro Looks like my job of answering "why?" was already done by David and Dana.

**Comment by itamaro** [comment]
@modi-resonai I think I understand the need to get the settings file path, what I'm not clear about is how this makes it easier, as opposed to doing `from yabt.config import YSETTINGS_FILE` wherever it is needed?

**Pull request merged**
