### PR TITLE
removing python 3.5, adding python 3.9

### PR DESCRIPTION
**Pull request by dlehavi-resonai**

### CODE REVIEW

**Comment by dlehavi-resonai** [comment]
https://travis-ci.community/t/build-error-for-python-3-7-on-two-different-projects/12895

**Review by shirl-resonai — APPROVED** [review]

**Comment by itamaro** [comment]
Can you add 3.10 too?

Is there anything in the codebase that's broken with 3.5, or just CI no longer plays nice with it?

**Comment by dlehavi-resonai** [comment]
@itamaro The problem is appveyor, which by now does not support 3.5, and does not even support 3.9 (yet..). I feel somewhat bad about running travis with 3.9 and appveyor w/o it, but I had to since resonai2 is now 3.9, but I really don't want to bump it to 3.10 without a reason until appveyor support it. Does it make sense ?

**Comment by itamaro** [comment]
Are there users that actually run ybt on Windows? (in resonai or otherwise)
I don't see any issue with running Travis with 3.10 too, as long as there's a version overlap between Travis and appveyor. Travis would help catching future deprecations earlier this way.

**Comment by dlehavi-resonai** [comment]
@itamaro : We are not aware of anyone out of Resonai. and AFAIK no one runs it on Windows here. I'll add 3.10 in the next PR.

**Pull request merged**
